name: Terraform CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Terraform Format, Validate, Plan, Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false -var="vpc_cidr=10.0.0.0/16" -var="env_name=staging"

    - name: Terraform Apply (Step 1 - VPC/Subnets)
      if: github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve -input=false \
          -target=module.vpc \
          -target=module.public_subnet_1 \
          -target=module.public_subnet_2 \
          -var="vpc_cidr=10.0.0.0/16" \
          -var="env_name=staging"

    - name: Terraform Apply (Step 2 - Remaining Modules)
      if: github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve -input=false \
          -var="vpc_cidr=10.0.0.0/16" \
          -var="env_name=staging"

    - name: Trigger Ansible Workflow
      if: success()
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/stevie1mat/ansible-final-project/actions/workflows/run-ansible.yml/dispatches \
          -d '{"ref":"main"}'
